# Overriding the default configuration of Eureka when running in a cloud environment
server:
  hostname: localhost
  port: 8761
  zone: primary
  region: IN

spring:
  application:
    name: Service-Registry

eureka:
  datacenter: cloud
  environment: ${spring.profiles.active}

  instance:
    hostname: ${server.hostname}
    instanceId: ${server.hostname}:${server.port}
    metadataMap:
      zone: ${server.zone}

  client:
    region: ${server.region}
    availability-zones:
      IN: BR,BLR
    service-url:
      BR: http://eureka-server1:8761/eureka/
      BLR: http://eureka-server2:8762/eureka/
