services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - order_mysql:/var/lib/mysql

volumes:
  order_mysql:

