server:
  hostname: localhost
  port: 9085
  region: IN
  zone: BR

eureka:
  client:
    register-with-eureka: false
    region: IN
    availability-zones:
      IN: BR,BLR
    service-url:
      BR: http://eureka-server1:8761/eureka/
      BLR: http://eureka-server2:8762/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/order_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.upendra.order_service: debug