server:
  hostname: localhost
  port: 9085
  region: IN
  zone: BR

spring:
  application:
    name: inventory-service
    version: 1.0.0
    description: Order Service API
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  datacenter: cloud
  environment: ${spring.profiles.active}

  instance:
    hostname: ${server.hostname}
    instanceId: ${server.hostname}:${server.port}
    metadataMap:
      zone: ${server.zone}

  client:
    region: ${server.region}
    fetch-registry: false
    availability-zones:
      IN: BR,BLR
    service-url:
      BR: http://eureka-server1:8761/eureka/
      BLR: http://eureka-server2:8762/eureka/