server:
  hostname: localhost
  port: 9080
  region: IN
  zone: BR

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/product-service?authSource=admin

eureka:
  client:
    region: IN
    availability-zones:
      IN: BR,BLR
    service-url:
      BR: http://eureka-server1:8761/eureka/
      BLR: http://eureka-server2:8762/eureka/

logging:
  level:
    com.upendra.product_service: debug