server:
    port: 8080

spring:
  application:
    name: product-service
    description: Product Service API
    version: 1.0.0

eureka:
  instance:
    hostname: ${server.hostname}
    instanceId: ${server.hostname}:${server.port}
    metadataMap:
      zone: ${server.zone}

#  Client is configured in profile specific as it depends on server configuration

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httpexchanges:
      enabled: true